// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ReverieHouse","status":false,"description":"","parameters":{}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,6","mPadding":"5,5,5,5","invertPos":"false","aGraphic":"","yOffset":"72"}},
{"name":"StopMovement","status":true,"description":"Stops player/NPC movement based on switches.","parameters":{"PC Switch ID":"105","NPC Switch ID":"106"}}
];
